/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import br.edu.uerr.appportariasolo.controler.FuncionarioJpaController;
import br.edu.uerr.appportariasolo.controler.PessoaGeralJpaController;
import br.edu.uerr.appportariasolo.controler.SetorJpaController;
import br.edu.uerr.appportariasolo.modelo.Funcionario;
import br.edu.uerr.appportariasolo.modelo.PessoaGeral;
import br.edu.uerr.appportariasolo.modelo.Setor;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author DevSilva
 */
public class TelaCadastroFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroFuncionario
     */
    public TelaCadastroFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jRg = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jCpf = new javax.swing.JLabel();
        vCep = new javax.swing.JFormattedTextField();
        jDt = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        vDatadeAdimicao = new javax.swing.JFormattedTextField();
        jMatri = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        vMatricula = new javax.swing.JFormattedTextField();
        jSetor = new javax.swing.JLabel();
        vCpf = new javax.swing.JTextField();
        jRua = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        vRua = new javax.swing.JTextField();
        jNumCasa = new javax.swing.JLabel();
        vNumero = new javax.swing.JTextField();
        jairro = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        vBairro = new javax.swing.JTextField();
        jCep = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        vTelefone = new javax.swing.JFormattedTextField();
        Cjcidad = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        vCidade = new javax.swing.JTextField();
        jEmail = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        vEmail = new javax.swing.JTextField();
        jTelef = new javax.swing.JLabel();
        jSeparator23 = new javax.swing.JSeparator();
        vCelular = new javax.swing.JFormattedTextField();
        jClular = new javax.swing.JLabel();
        jSeparator24 = new javax.swing.JSeparator();
        jbCadastrar = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jbLimpar = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jGen = new javax.swing.JLabel();
        jNome = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jUf = new javax.swing.JLabel();
        vUf = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        vCampoAlunoOut = new javax.swing.JCheckBox();
        vCampoAlunoMasc = new javax.swing.JCheckBox();
        vCampoAlunoFem = new javax.swing.JCheckBox();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        vSetor = new javax.swing.JComboBox<>();
        jDt1 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        vDataDeNascimento = new javax.swing.JFormattedTextField();
        jLfechar1 = new javax.swing.JLabel();
        jLfechar = new javax.swing.JLabel();
        vNome = new javax.swing.JTextField();
        vRg = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 500, 10));

        jRg.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jRg.setForeground(new java.awt.Color(0, 51, 102));
        jRg.setText("RG:");
        jPanel1.add(jRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 50, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 140, 10));

        jCpf.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jCpf.setForeground(new java.awt.Color(0, 51, 102));
        jCpf.setText("CPF:");
        jPanel1.add(jCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 30, -1));

        vCep.setBackground(new java.awt.Color(204, 204, 204));
        vCep.setBorder(null);
        vCep.setForeground(new java.awt.Color(153, 153, 153));
        try {
            vCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        vCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vCepActionPerformed(evt);
            }
        });
        jPanel1.add(vCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 70, -1));

        jDt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jDt.setForeground(new java.awt.Color(0, 51, 102));
        jDt.setText("Data de Nasc:");
        jPanel1.add(jDt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 100, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 70, -1));

        vDatadeAdimicao.setBackground(new java.awt.Color(204, 204, 204));
        vDatadeAdimicao.setBorder(null);
        vDatadeAdimicao.setForeground(new java.awt.Color(153, 153, 153));
        try {
            vDatadeAdimicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        vDatadeAdimicao.setText("00/00/0000");
        vDatadeAdimicao.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vDatadeAdimicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vDatadeAdimicaoMouseClicked(evt);
            }
        });
        jPanel1.add(vDatadeAdimicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 80, -1));

        jMatri.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jMatri.setForeground(new java.awt.Color(0, 51, 102));
        jMatri.setText("Matricula (Codigo):");
        jPanel1.add(jMatri, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 140, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 130, 10));

        vMatricula.setBackground(new java.awt.Color(204, 204, 204));
        vMatricula.setBorder(null);
        vMatricula.setForeground(new java.awt.Color(153, 153, 153));
        vMatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));
        vMatricula.setText("Somente números");
        vMatricula.setCaretColor(new java.awt.Color(153, 153, 153));
        vMatricula.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vMatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vMatriculaMouseClicked(evt);
            }
        });
        jPanel1.add(vMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 130, -1));

        jSetor.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jSetor.setForeground(new java.awt.Color(0, 51, 102));
        jSetor.setText("Setor:");
        jPanel1.add(jSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 50, -1));

        vCpf.setBackground(new java.awt.Color(204, 204, 204));
        vCpf.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vCpf.setForeground(new java.awt.Color(153, 153, 153));
        vCpf.setText("Somente números");
        vCpf.setBorder(null);
        vCpf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vCpfMouseClicked(evt);
            }
        });
        jPanel1.add(vCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 140, -1));

        jRua.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jRua.setForeground(new java.awt.Color(0, 51, 102));
        jRua.setText("Rua:");
        jPanel1.add(jRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 50, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 360, 10));

        vRua.setBackground(new java.awt.Color(204, 204, 204));
        vRua.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vRua.setForeground(new java.awt.Color(153, 153, 153));
        vRua.setBorder(null);
        jPanel1.add(vRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 360, -1));

        jNumCasa.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jNumCasa.setForeground(new java.awt.Color(0, 51, 102));
        jNumCasa.setText("Número:");
        jPanel1.add(jNumCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        vNumero.setBackground(new java.awt.Color(204, 204, 204));
        vNumero.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vNumero.setForeground(new java.awt.Color(153, 153, 153));
        vNumero.setBorder(null);
        jPanel1.add(vNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 70, -1));

        jairro.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jairro.setForeground(new java.awt.Color(0, 51, 102));
        jairro.setText("Bairro:");
        jPanel1.add(jairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 50, -1));
        jPanel1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 180, 10));

        vBairro.setBackground(new java.awt.Color(204, 204, 204));
        vBairro.setForeground(new java.awt.Color(153, 153, 153));
        vBairro.setBorder(null);
        jPanel1.add(vBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 180, -1));

        jCep.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jCep.setForeground(new java.awt.Color(0, 51, 102));
        jCep.setText("CEP:");
        jPanel1.add(jCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));
        jPanel1.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 80, 10));

        vTelefone.setBackground(new java.awt.Color(204, 204, 204));
        vTelefone.setBorder(null);
        vTelefone.setForeground(new java.awt.Color(153, 153, 153));
        try {
            vTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        vTelefone.setText("(00)0000-0000");
        vTelefone.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vTelefoneMouseClicked(evt);
            }
        });
        jPanel1.add(vTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 100, -1));

        Cjcidad.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Cjcidad.setForeground(new java.awt.Color(0, 51, 102));
        Cjcidad.setText("Cidade:");
        jPanel1.add(Cjcidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 60, -1));
        jPanel1.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 130, 10));

        vCidade.setBackground(new java.awt.Color(204, 204, 204));
        vCidade.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vCidade.setForeground(new java.awt.Color(153, 153, 153));
        vCidade.setBorder(null);
        jPanel1.add(vCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 110, -1));

        jEmail.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jEmail.setForeground(new java.awt.Color(0, 51, 102));
        jEmail.setText("Email:");
        jPanel1.add(jEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 50, -1));
        jPanel1.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 280, 10));

        vEmail.setBackground(new java.awt.Color(204, 204, 204));
        vEmail.setForeground(new java.awt.Color(153, 153, 153));
        vEmail.setBorder(null);
        jPanel1.add(vEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 290, -1));

        jTelef.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTelef.setForeground(new java.awt.Color(0, 51, 102));
        jTelef.setText("Telefone:");
        jPanel1.add(jTelef, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 70, -1));
        jPanel1.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 110, 10));

        vCelular.setBackground(new java.awt.Color(204, 204, 204));
        vCelular.setBorder(null);
        vCelular.setForeground(new java.awt.Color(153, 153, 153));
        try {
            vCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        vCelular.setText("(00)00000-0000");
        vCelular.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vCelular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vCelularMouseClicked(evt);
            }
        });
        jPanel1.add(vCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 110, -1));

        jClular.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jClular.setForeground(new java.awt.Color(0, 51, 102));
        jClular.setText("Celular:");
        jPanel1.add(jClular, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 70, -1));
        jPanel1.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 120, 10));

        jbCadastrar.setBackground(new java.awt.Color(0, 51, 102));
        jbCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCadastrarMouseClicked(evt);
            }
        });
        jbCadastrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("CADASTRAR");
        jbCadastrar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 0, -1, 30));

        jPanel1.add(jbCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, 120, 30));

        jbLimpar.setBackground(new java.awt.Color(0, 51, 102));
        jbLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbLimparMouseClicked(evt);
            }
        });
        jbLimpar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("LIMPAR");
        jbLimpar.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 0, -1, 30));

        jPanel1.add(jbLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 120, -1));

        jGen.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jGen.setForeground(new java.awt.Color(0, 51, 102));
        jGen.setText("Género:");
        jPanel1.add(jGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 70, -1));

        jNome.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jNome.setForeground(new java.awt.Color(0, 51, 102));
        jNome.setText("Nome:");
        jPanel1.add(jNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 50, -1));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 140, 10));

        jUf.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jUf.setForeground(new java.awt.Color(0, 51, 102));
        jUf.setText("UF:");
        jPanel1.add(jUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 30, -1));

        vUf.setBackground(new java.awt.Color(204, 204, 204));
        vUf.setForeground(new java.awt.Color(153, 153, 153));
        vUf.setBorder(null);
        jPanel1.add(vUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 40, -1));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 40, 10));

        vCampoAlunoOut.setBackground(new java.awt.Color(204, 204, 204));
        vCampoAlunoOut.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vCampoAlunoOut.setForeground(new java.awt.Color(153, 153, 153));
        vCampoAlunoOut.setText("Outro");
        vCampoAlunoOut.setBorder(null);
        vCampoAlunoOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vCampoAlunoOutActionPerformed(evt);
            }
        });
        jPanel1.add(vCampoAlunoOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));

        vCampoAlunoMasc.setBackground(new java.awt.Color(204, 204, 204));
        vCampoAlunoMasc.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vCampoAlunoMasc.setForeground(new java.awt.Color(153, 153, 153));
        vCampoAlunoMasc.setText("Masculino");
        vCampoAlunoMasc.setBorder(null);
        vCampoAlunoMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vCampoAlunoMascActionPerformed(evt);
            }
        });
        jPanel1.add(vCampoAlunoMasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        vCampoAlunoFem.setBackground(new java.awt.Color(204, 204, 204));
        vCampoAlunoFem.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vCampoAlunoFem.setForeground(new java.awt.Color(153, 153, 153));
        vCampoAlunoFem.setText("Feminino");
        vCampoAlunoFem.setBorder(null);
        vCampoAlunoFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vCampoAlunoFemActionPerformed(evt);
            }
        });
        jPanel1.add(vCampoAlunoFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 90, 10));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 290, 10));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 102));
        jLabel15.setText("DADOS PESSOAIS");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 40));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 680, -1));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 102));
        jLabel18.setText("DADOS PROFISSIONAIS");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 200, 40));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 680, -1));

        vSetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum Setor", "Multiteca", "Registro Acadêmico", "Almoxarifado", "Asessoria de Cominicação", "Asessoria de Comunicação", "Auditorio", "Comissão de Ética", "Controle Interno", "Conuni", "Convênio", "Copa", "Nenhum Setor", "CPL e Seção de Compras", "Comussão Permanente de Concurso e Vestibular", "Departamento de Desenvolvimento Pessoal", "Departamento de Logística", "Departamento de Planejamento Estratégico", "Departamento de Pós-graduação", "Divisão de Cadastro de Pessoal", "Telemática", "Dvisão de Transporte", "Guarita", "Labtema", "Núcleo de Prátca Jurídica", "Projur", "Protocolo", "Recepção Gabinete" }));
        jPanel1.add(vSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 160, 30));

        jDt1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jDt1.setForeground(new java.awt.Color(0, 51, 102));
        jDt1.setText("Data de Admição:");
        jPanel1.add(jDt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 130, -1));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 80, 10));

        vDataDeNascimento.setBackground(new java.awt.Color(204, 204, 204));
        vDataDeNascimento.setBorder(null);
        vDataDeNascimento.setForeground(new java.awt.Color(153, 153, 153));
        try {
            vDataDeNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        vDataDeNascimento.setText("00/00/0000");
        vDataDeNascimento.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vDataDeNascimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vDataDeNascimentoMouseClicked(evt);
            }
        });
        jPanel1.add(vDataDeNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 80, -1));

        jLfechar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img_fexar.png"))); // NOI18N
        jLfechar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLfechar1MouseClicked(evt);
            }
        });
        jPanel1.add(jLfechar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, 30));

        jLfechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img_home.png"))); // NOI18N
        jLfechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLfecharMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLfecharMousePressed(evt);
            }
        });
        jPanel1.add(jLfechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, 30));

        vNome.setBackground(new java.awt.Color(204, 204, 204));
        vNome.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vNome.setForeground(new java.awt.Color(153, 153, 153));
        vNome.setText("Digite o nome comleto");
        vNome.setBorder(null);
        vNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vNomeMouseClicked(evt);
            }
        });
        jPanel1.add(vNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 500, -1));

        vRg.setBackground(new java.awt.Color(204, 204, 204));
        vRg.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vRg.setForeground(new java.awt.Color(153, 153, 153));
        vRg.setText("Somente números");
        vRg.setBorder(null);
        vRg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vRgMouseClicked(evt);
            }
        });
        jPanel1.add(vRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(680, 540));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void vCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vCepActionPerformed

    private void vDatadeAdimicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vDatadeAdimicaoMouseClicked
        vDatadeAdimicao.setText("");
    }//GEN-LAST:event_vDatadeAdimicaoMouseClicked

    private void vMatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vMatriculaMouseClicked
        vMatricula.setText("");
    }//GEN-LAST:event_vMatriculaMouseClicked

    private void vCpfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vCpfMouseClicked
        vCpf.setText("");
    }//GEN-LAST:event_vCpfMouseClicked

    private void vTelefoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vTelefoneMouseClicked
        vTelefone.setText("");
    }//GEN-LAST:event_vTelefoneMouseClicked

    private void vCelularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vCelularMouseClicked
        vCelular.setText("");
    }//GEN-LAST:event_vCelularMouseClicked

    private void vCampoAlunoOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vCampoAlunoOutActionPerformed
        if (vCampoAlunoMasc.isSelected() || vCampoAlunoFem.isSelected()) {
            vCampoAlunoMasc.setSelected(false);
            vCampoAlunoFem.setSelected(false);

        }
    }//GEN-LAST:event_vCampoAlunoOutActionPerformed

    private void vCampoAlunoMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vCampoAlunoMascActionPerformed
        if (vCampoAlunoOut.isSelected() || vCampoAlunoFem.isSelected()) {
            vCampoAlunoOut.setSelected(false);
            vCampoAlunoFem.setSelected(false);

        }
    }//GEN-LAST:event_vCampoAlunoMascActionPerformed

    private void vCampoAlunoFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vCampoAlunoFemActionPerformed
        if (vCampoAlunoMasc.isSelected() || vCampoAlunoOut.isSelected()) {
            vCampoAlunoMasc.setSelected(false);
            vCampoAlunoOut.setSelected(false);

        }
    }//GEN-LAST:event_vCampoAlunoFemActionPerformed

    private void vDataDeNascimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vDataDeNascimentoMouseClicked
        // TODO add your handling code here:
        vDataDeNascimento.setText("");
    }//GEN-LAST:event_vDataDeNascimentoMouseClicked

    private void jLfechar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLfechar1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLfechar1MouseClicked

    private void jLfecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLfecharMouseClicked

    }//GEN-LAST:event_jLfecharMouseClicked

    private void jLfecharMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLfecharMousePressed
        // TODO add your handling code here:
        new TelaMenu().show();
    }//GEN-LAST:event_jLfecharMousePressed

    private void jbLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbLimparMouseClicked
        // TODO add your handling code here:
        vCpf.setText("");
        vBairro.setText("");
        vCelular.setText("");
        vCep.setText("");
        vCidade.setText("");
        vRg.setText("");
        vDataDeNascimento.setText("");
        vDatadeAdimicao.setText("");
        vEmail.setText("");
        vCpf.setText("");
        vMatricula.setText("");
        vNumero.setText("");
        vRg.setText("");
        vRua.setText("");
        vTelefone.setText("");
        vUf.setText("");
    }//GEN-LAST:event_jbLimparMouseClicked

    private void jbCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCadastrarMouseClicked
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("apportariasoloPU");
        PessoaGeralJpaController pessoaJpaController = new PessoaGeralJpaController(emf);
        FuncionarioJpaController funcionarioJpaController = new FuncionarioJpaController(emf);
        SetorJpaController setorJpaController = new SetorJpaController(emf);
        Setor setor = new Setor();
        List<PessoaGeral> listaPessoa = new ArrayList<>();
        List<Setor> listaSetor = new ArrayList<>();
        //listaPessoa = pessoaJpaController.listaUltimouatro();
        System.out.println("");

        // for (PessoaGeral pessoa : listaPessoa) {
        // System.out.println(pessoa.toString());
        //}
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        //criando o objeto, importara dados do modelo pessoa
        String msg = "";
        int erro = 0;
        String idSetorPego = null;
        int idSetor = 0;
        //String sexo = (String) vSexo.getSelectedItem();
        String setorN = (String) vSetor.getSelectedItem();
        //Integer fkpg=0;
        //DefaultTableModel TempTabela = new DefaultTableModel(colunas,0);
        PessoaGeral pessoa = new PessoaGeral();
        //fkpg=pessoa.getIdPessoaGeral();
        pessoa.setNome(vNome.getText());
        pessoa.setCpf(vCpf.getText());
        pessoa.setEmail(vEmail.getText());
        pessoa.setCelular(vCelular.getText());
        pessoa.setBairro(vBairro.getText());
        pessoa.setNumero(vNumero.getText());
        pessoa.setRg(vRg.getText());
        pessoa.setTelefone(vTelefone.getText());
        pessoa.setCep(vCep.getText());
        pessoa.setEndereco(vRua.getText());
        pessoa.setCidade(vCidade.getText());
        pessoa.setUf(vUf.getText());
        //pessoa.setSexo(vSexo.setSelectedItem(ABORT));

        Funcionario funcionario = new Funcionario();
        //funcionario.setConta(vConta.getText());
        funcionario.setMatricula(vMatricula.getText());
        //funcionario.setSenha(vSenha.getText());

        if (pessoa.getNome().isEmpty()) {
            msg = msg + "\n Nome é obrigatorio";
            erro++;
        }
        if (pessoa.getCpf().isEmpty()) {
            msg = msg + "\n CPF é obrigatorio";
            erro++;
        }
        //if (sexo == "Masculino") {
         //   pessoa.setSexo(1);
        //} else {
         //   pessoa.setSexo(2);
        //}
        if(vCampoAlunoMasc.isSelected()){
            pessoa.setSexo(1);
        }
        if(vCampoAlunoFem.isSelected()){
            pessoa.setSexo(2);
        }
        if(vCampoAlunoOut.isSelected()){
            pessoa.setSexo(3);
        }

        try {

            listaSetor = setorJpaController.listaSetor(setorN);
            for (int i = 0; i <= listaPessoa.size(); i++) {
                idSetorPego = String.valueOf(listaSetor.get(i));
                idSetor = Integer.valueOf(idSetorPego);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        funcionario.setIdSetorFk(new Setor());
        setor = setorJpaController.findSetor(idSetor);
        funcionario.setIdSetorFk(setor);

        if (erro > 0) {
            JOptionPane.showMessageDialog(null, msg);
        } else {
            try {
                JOptionPane.showMessageDialog(null, msg);
                if (!vDataDeNascimento.getText().isEmpty()) {
                    pessoa.setDatadenascimento((Date) dateFormat.parse(vDataDeNascimento.getText()));
                }
                if (!vDatadeAdimicao.getText().isEmpty()) {
                    funcionario.setDataIn((Date) dateFormat.parse(vDatadeAdimicao.getText()));
                }

                pessoaJpaController.create(pessoa);
                funcionario.setIdPessoaGeralFk(pessoa);
                funcionarioJpaController.create(funcionario);
                JOptionPane.showMessageDialog(null, "Funcionario Cadastrado com Sucesso");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }


    }//GEN-LAST:event_jbCadastrarMouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        //int x = evt.getXOnScreen();
        //int y = evt.getYOnScreen();
        //this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged
        //int xx,xy;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        //xx = evt.getX();
        //xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void vNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vNomeMouseClicked
        // TODO add your handling code here:
        vNome.setText("");
        
    }//GEN-LAST:event_vNomeMouseClicked

    private void vRgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vRgMouseClicked
        // TODO add your handling code here:
        vRg.setText("");
    }//GEN-LAST:event_vRgMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cjcidad;
    private javax.swing.JLabel jCep;
    private javax.swing.JLabel jClular;
    private javax.swing.JLabel jCpf;
    private javax.swing.JLabel jDt;
    private javax.swing.JLabel jDt1;
    private javax.swing.JLabel jEmail;
    private javax.swing.JLabel jGen;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLfechar;
    private javax.swing.JLabel jLfechar1;
    private javax.swing.JLabel jMatri;
    private javax.swing.JLabel jNome;
    private javax.swing.JLabel jNumCasa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jRg;
    private javax.swing.JLabel jRua;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel jSetor;
    private javax.swing.JLabel jTelef;
    private javax.swing.JLabel jUf;
    private javax.swing.JLabel jairro;
    private javax.swing.JPanel jbCadastrar;
    private javax.swing.JPanel jbLimpar;
    private javax.swing.JTextField vBairro;
    private javax.swing.JCheckBox vCampoAlunoFem;
    private javax.swing.JCheckBox vCampoAlunoMasc;
    private javax.swing.JCheckBox vCampoAlunoOut;
    private javax.swing.JFormattedTextField vCelular;
    private javax.swing.JFormattedTextField vCep;
    private javax.swing.JTextField vCidade;
    private javax.swing.JTextField vCpf;
    private javax.swing.JFormattedTextField vDataDeNascimento;
    private javax.swing.JFormattedTextField vDatadeAdimicao;
    private javax.swing.JTextField vEmail;
    private javax.swing.JFormattedTextField vMatricula;
    private javax.swing.JTextField vNome;
    private javax.swing.JTextField vNumero;
    private javax.swing.JTextField vRg;
    private javax.swing.JTextField vRua;
    private javax.swing.JComboBox<String> vSetor;
    private javax.swing.JFormattedTextField vTelefone;
    private javax.swing.JTextField vUf;
    // End of variables declaration//GEN-END:variables
}
