/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import br.edu.uerr.appportariasolo.controler.AlunoJpaController;
import br.edu.uerr.appportariasolo.controler.CursoJpaController;
import br.edu.uerr.appportariasolo.controler.PessoaGeralJpaController;
import br.edu.uerr.appportariasolo.controler.SetorJpaController;
import br.edu.uerr.appportariasolo.modelo.Aluno;
import br.edu.uerr.appportariasolo.modelo.Curso;
import br.edu.uerr.appportariasolo.modelo.PessoaGeral;
import br.edu.uerr.appportariasolo.modelo.Setor;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author DevSilva
 */
public class TelaCadastroAluno extends javax.swing.JFrame {

    /**
     * Creates new form TelaDesk
     */
    public TelaCadastroAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jRg = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jCpf = new javax.swing.JLabel();
        vCep = new javax.swing.JFormattedTextField();
        jDt = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        vDataNascimento = new javax.swing.JFormattedTextField();
        jMatri = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        vMatricula = new javax.swing.JFormattedTextField();
        jSetor = new javax.swing.JLabel();
        vRg = new javax.swing.JTextField();
        jCur = new javax.swing.JLabel();
        jRua = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        vRua = new javax.swing.JTextField();
        jNumCasa = new javax.swing.JLabel();
        vNumero = new javax.swing.JTextField();
        jairro = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        vBairro = new javax.swing.JTextField();
        jCep = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        vCelular = new javax.swing.JFormattedTextField();
        Cjcidad = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        vCidade = new javax.swing.JTextField();
        jEmail = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        vEmail = new javax.swing.JTextField();
        jTelef = new javax.swing.JLabel();
        jSeparator23 = new javax.swing.JSeparator();
        jClular = new javax.swing.JLabel();
        jSeparator24 = new javax.swing.JSeparator();
        jbCadastrar = new javax.swing.JPanel();
        jbCadastra = new javax.swing.JLabel();
        jbLimpar = new javax.swing.JPanel();
        jbLimpa = new javax.swing.JLabel();
        jGen = new javax.swing.JLabel();
        jNome = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jUf = new javax.swing.JLabel();
        vUf = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        vCampoAlunoOut = new javax.swing.JCheckBox();
        vCampoAlunoMasc = new javax.swing.JCheckBox();
        vCampoAlunoFem = new javax.swing.JCheckBox();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        vCurso = new javax.swing.JComboBox<>();
        vSetor = new javax.swing.JComboBox<>();
        jLfechar1 = new javax.swing.JLabel();
        jLfechar = new javax.swing.JLabel();
        vTelefone = new javax.swing.JFormattedTextField();
        vNome = new javax.swing.JTextField();
        vCpf = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanelPortaria = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelVisitantes = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelAlunos = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jPanelFuncionarios = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 540));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 500, 10));

        jRg.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jRg.setForeground(new java.awt.Color(0, 51, 102));
        jRg.setText("RG:");
        jPanel1.add(jRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 50, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 140, 10));

        jCpf.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jCpf.setForeground(new java.awt.Color(0, 51, 102));
        jCpf.setText("CPF:");
        jPanel1.add(jCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 50, -1));

        vCep.setBackground(new java.awt.Color(204, 204, 204));
        vCep.setBorder(null);
        vCep.setForeground(new java.awt.Color(153, 153, 153));
        try {
            vCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        vCep.setText("00.000-000");
        vCep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vCep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vCepMouseClicked(evt);
            }
        });
        jPanel1.add(vCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 80, -1));

        jDt.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jDt.setForeground(new java.awt.Color(0, 51, 102));
        jDt.setText("Data de Nasc:");
        jPanel1.add(jDt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 100, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 70, -1));

        vDataNascimento.setBackground(new java.awt.Color(204, 204, 204));
        vDataNascimento.setBorder(null);
        vDataNascimento.setForeground(new java.awt.Color(153, 153, 153));
        try {
            vDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        vDataNascimento.setText("00/00/0000");
        vDataNascimento.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vDataNascimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vDataNascimentoMouseClicked(evt);
            }
        });
        jPanel1.add(vDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 80, -1));

        jMatri.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jMatri.setForeground(new java.awt.Color(0, 51, 102));
        jMatri.setText("Matricula:");
        jPanel1.add(jMatri, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 70, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 130, 10));

        vMatricula.setBackground(new java.awt.Color(204, 204, 204));
        vMatricula.setBorder(null);
        vMatricula.setForeground(new java.awt.Color(153, 153, 153));
        vMatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));
        vMatricula.setText("Somente números");
        vMatricula.setCaretColor(new java.awt.Color(153, 153, 153));
        vMatricula.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vMatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vMatriculaMouseClicked(evt);
            }
        });
        jPanel1.add(vMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 130, -1));

        jSetor.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jSetor.setForeground(new java.awt.Color(0, 51, 102));
        jSetor.setText("Setor:");
        jPanel1.add(jSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 50, -1));

        vRg.setBackground(new java.awt.Color(204, 204, 204));
        vRg.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vRg.setForeground(new java.awt.Color(153, 153, 153));
        vRg.setText("Somente números");
        vRg.setBorder(null);
        vRg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vRgMouseClicked(evt);
            }
        });
        jPanel1.add(vRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 130, -1));

        jCur.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jCur.setForeground(new java.awt.Color(0, 51, 102));
        jCur.setText("Curso:");
        jPanel1.add(jCur, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 50, -1));

        jRua.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jRua.setForeground(new java.awt.Color(0, 51, 102));
        jRua.setText("Rua:");
        jPanel1.add(jRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 50, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 360, 10));

        vRua.setBackground(new java.awt.Color(204, 204, 204));
        vRua.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vRua.setForeground(new java.awt.Color(153, 153, 153));
        vRua.setBorder(null);
        jPanel1.add(vRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 360, -1));

        jNumCasa.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jNumCasa.setForeground(new java.awt.Color(0, 51, 102));
        jNumCasa.setText("Número:");
        jPanel1.add(jNumCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        vNumero.setBackground(new java.awt.Color(204, 204, 204));
        vNumero.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vNumero.setForeground(new java.awt.Color(153, 153, 153));
        vNumero.setBorder(null);
        jPanel1.add(vNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 70, -1));

        jairro.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jairro.setForeground(new java.awt.Color(0, 51, 102));
        jairro.setText("Bairro:");
        jPanel1.add(jairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 50, -1));
        jPanel1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 180, 10));

        vBairro.setBackground(new java.awt.Color(204, 204, 204));
        vBairro.setForeground(new java.awt.Color(153, 153, 153));
        vBairro.setBorder(null);
        jPanel1.add(vBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 180, -1));

        jCep.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jCep.setForeground(new java.awt.Color(0, 51, 102));
        jCep.setText("CEP:");
        jPanel1.add(jCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));
        jPanel1.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 80, 10));

        vCelular.setBackground(new java.awt.Color(204, 204, 204));
        vCelular.setBorder(null);
        vCelular.setForeground(new java.awt.Color(153, 153, 153));
        try {
            vCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        vCelular.setText("(00)00000-0000");
        vCelular.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vCelular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vCelularMouseClicked(evt);
            }
        });
        jPanel1.add(vCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 110, -1));

        Cjcidad.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Cjcidad.setForeground(new java.awt.Color(0, 51, 102));
        Cjcidad.setText("Cidade:");
        jPanel1.add(Cjcidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 60, -1));
        jPanel1.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 130, 10));

        vCidade.setBackground(new java.awt.Color(204, 204, 204));
        vCidade.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vCidade.setForeground(new java.awt.Color(153, 153, 153));
        vCidade.setBorder(null);
        jPanel1.add(vCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 110, -1));

        jEmail.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jEmail.setForeground(new java.awt.Color(0, 51, 102));
        jEmail.setText("Email:");
        jPanel1.add(jEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 50, -1));
        jPanel1.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 290, 10));

        vEmail.setBackground(new java.awt.Color(204, 204, 204));
        vEmail.setForeground(new java.awt.Color(153, 153, 153));
        vEmail.setBorder(null);
        jPanel1.add(vEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 290, -1));

        jTelef.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTelef.setForeground(new java.awt.Color(0, 51, 102));
        jTelef.setText("Telefone:");
        jPanel1.add(jTelef, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 70, -1));
        jPanel1.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 120, 10));

        jClular.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jClular.setForeground(new java.awt.Color(0, 51, 102));
        jClular.setText("Celular:");
        jPanel1.add(jClular, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 70, -1));
        jPanel1.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 120, 10));

        jbCadastrar.setBackground(new java.awt.Color(0, 51, 102));
        jbCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCadastrarMouseClicked(evt);
            }
        });
        jbCadastrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbCadastra.setBackground(new java.awt.Color(255, 255, 255));
        jbCadastra.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jbCadastra.setForeground(new java.awt.Color(255, 255, 255));
        jbCadastra.setText("CADASTRAR");
        jbCadastrar.add(jbCadastra, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 0, -1, 30));

        jPanel1.add(jbCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, 120, 30));

        jbLimpar.setBackground(new java.awt.Color(0, 51, 102));
        jbLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbLimparMouseClicked(evt);
            }
        });
        jbLimpar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbLimpa.setBackground(new java.awt.Color(255, 255, 255));
        jbLimpa.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jbLimpa.setForeground(new java.awt.Color(255, 255, 255));
        jbLimpa.setText("LIMPAR");
        jbLimpar.add(jbLimpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 0, -1, 30));

        jPanel1.add(jbLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 120, -1));

        jGen.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jGen.setForeground(new java.awt.Color(0, 51, 102));
        jGen.setText("Género:");
        jPanel1.add(jGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 70, -1));

        jNome.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jNome.setForeground(new java.awt.Color(0, 51, 102));
        jNome.setText("Nome:");
        jPanel1.add(jNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 50, -1));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 130, 10));

        jUf.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jUf.setForeground(new java.awt.Color(0, 51, 102));
        jUf.setText("UF:");
        jPanel1.add(jUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 30, -1));

        vUf.setBackground(new java.awt.Color(204, 204, 204));
        vUf.setForeground(new java.awt.Color(153, 153, 153));
        vUf.setBorder(null);
        jPanel1.add(vUf, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 20, -1));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 40, 10));

        vCampoAlunoOut.setBackground(new java.awt.Color(204, 204, 204));
        vCampoAlunoOut.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vCampoAlunoOut.setForeground(new java.awt.Color(153, 153, 153));
        vCampoAlunoOut.setText("Outro");
        vCampoAlunoOut.setBorder(null);
        vCampoAlunoOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vCampoAlunoOutActionPerformed(evt);
            }
        });
        jPanel1.add(vCampoAlunoOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));

        vCampoAlunoMasc.setBackground(new java.awt.Color(204, 204, 204));
        vCampoAlunoMasc.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vCampoAlunoMasc.setForeground(new java.awt.Color(153, 153, 153));
        vCampoAlunoMasc.setText("Masculino");
        vCampoAlunoMasc.setBorder(null);
        vCampoAlunoMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vCampoAlunoMascActionPerformed(evt);
            }
        });
        jPanel1.add(vCampoAlunoMasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        vCampoAlunoFem.setBackground(new java.awt.Color(204, 204, 204));
        vCampoAlunoFem.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vCampoAlunoFem.setForeground(new java.awt.Color(153, 153, 153));
        vCampoAlunoFem.setText("Feminino");
        vCampoAlunoFem.setBorder(null);
        vCampoAlunoFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vCampoAlunoFemActionPerformed(evt);
            }
        });
        jPanel1.add(vCampoAlunoFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 90, 10));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 290, 10));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 102));
        jLabel15.setText("DADOS DO ALUNO");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 40));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 680, -1));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 102));
        jLabel18.setText("DADOS ACADÊMICOS");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 200, 40));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 680, -1));

        vCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum Curso", "Administração", "Agronomia", "Ciências Biológicas", "Ciências da Computação", "Ciências da Natureza", "Ciências da Contábeis", "Comércio Exterior", "Direito", "Educação Física", "Enfermagem", "Engenharia Florestal", "Filosofia", "Física", "Geografica", "Historia", "Letras", "Matemática", "Pedagogia", "Química", "Segunrança Pública", "Serviço Social", "Sociologia", "Turismo", "Gestão e Docência do Ensino Superior", "Enfermagem Obstétrica", "Educação do Campo e suas Metodologias", "História da Amazônia", "Língua Portuguesa e Literatura", "Mestrado Profissional em Ensino de Ciências", "Mestrado Acadêmico em Biologia da Água Doce e Pesca Interior", "Mestrado Acadêmico em Agroecologia", "Mestrado Acadêmico em Educação", "Doutorado em Biologia da Água Doce e Pesca Interior", "Doutorado em Educação em Ciência e Matemática", "Doutorado Interinstitucional em Geografica", "Doutorado Interinstitucional em Letras e Linguística" }));
        jPanel1.add(vCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 280, 30));

        vSetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum Setor", "Multiteca", "Registro Acadêmico", "Almoxarifado", "Asessoria de Cominicação", "Asessoria de Comunicação", "Auditorio", "Comissão de Ética", "Controle Interno", "Conuni", "Convênio", "Copa", "CPL e Seção de Compras", "Comussão Permanente de Concurso e Vestibular", "Departamento de Desenvolvimento Pessoal", "Departamento de Logística", "Departamento de Planejamento Estratégico", "Departamento de Pós-graduação", "Divisão de Cadastro de Pessoal", "Telemática", "Dvisão de Transporte", "Guarita", "Labtema", "Núcleo de Prátca Jurídica", "Projur", "Protocolo", "Recepção Gabinete" }));
        jPanel1.add(vSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 160, 30));

        jLfechar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img_fexar.png"))); // NOI18N
        jLfechar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLfechar1MouseClicked(evt);
            }
        });
        jPanel1.add(jLfechar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, 30));

        jLfechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img_home.png"))); // NOI18N
        jLfechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLfecharMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLfecharMousePressed(evt);
            }
        });
        jPanel1.add(jLfechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, 30));

        vTelefone.setBackground(new java.awt.Color(204, 204, 204));
        vTelefone.setBorder(null);
        vTelefone.setForeground(new java.awt.Color(153, 153, 153));
        try {
            vTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        vTelefone.setText("(00)0000-0000");
        vTelefone.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vTelefoneMouseClicked(evt);
            }
        });
        jPanel1.add(vTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 100, -1));

        vNome.setBackground(new java.awt.Color(204, 204, 204));
        vNome.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vNome.setForeground(new java.awt.Color(153, 153, 153));
        vNome.setText("Digite o nome comleto");
        vNome.setBorder(null);
        vNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vNomeMouseClicked(evt);
            }
        });
        jPanel1.add(vNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 500, -1));

        vCpf.setBackground(new java.awt.Color(204, 204, 204));
        vCpf.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vCpf.setForeground(new java.awt.Color(153, 153, 153));
        vCpf.setText("Somente números");
        vCpf.setBorder(null);
        vCpf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vCpfMouseClicked(evt);
            }
        });
        jPanel1.add(vCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 680, 540));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPortaria.setBackground(new java.awt.Color(0, 51, 102));
        jPanelPortaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelPortariaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelPortariaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelPortariaMousePressed(evt);
            }
        });

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Portaria");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img_portaria.png"))); // NOI18N

        javax.swing.GroupLayout jPanelPortariaLayout = new javax.swing.GroupLayout(jPanelPortaria);
        jPanelPortaria.setLayout(jPanelPortariaLayout);
        jPanelPortariaLayout.setHorizontalGroup(
            jPanelPortariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPortariaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel25)
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPortariaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanelPortariaLayout.setVerticalGroup(
            jPanelPortariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPortariaLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanelPortaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 170, 110));

        jPanelVisitantes.setBackground(new java.awt.Color(0, 51, 102));
        jPanelVisitantes.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jPanelVisitantes.setPreferredSize(new java.awt.Dimension(170, 110));
        jPanelVisitantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelVisitantesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelVisitantesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelVisitantesMousePressed(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Visitantes");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img_visitantes.png"))); // NOI18N

        javax.swing.GroupLayout jPanelVisitantesLayout = new javax.swing.GroupLayout(jPanelVisitantes);
        jPanelVisitantes.setLayout(jPanelVisitantesLayout);
        jPanelVisitantesLayout.setHorizontalGroup(
            jPanelVisitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVisitantesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(jPanelVisitantesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel23)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanelVisitantesLayout.setVerticalGroup(
            jPanelVisitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVisitantesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );

        jPanel2.add(jPanelVisitantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 170, 110));

        jPanelAlunos.setBackground(new java.awt.Color(11, 100, 145));
        jPanelAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelAlunosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelAlunosMouseExited(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Alunos");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img_aluno.png"))); // NOI18N

        javax.swing.GroupLayout jPanelAlunosLayout = new javax.swing.GroupLayout(jPanelAlunos);
        jPanelAlunos.setLayout(jPanelAlunosLayout);
        jPanelAlunosLayout.setHorizontalGroup(
            jPanelAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlunosLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAlunosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanelAlunosLayout.setVerticalGroup(
            jPanelAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlunosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanelAlunos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 170, 110));
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jPanelFuncionarios.setBackground(new java.awt.Color(0, 51, 102));
        jPanelFuncionarios.setPreferredSize(new java.awt.Dimension(170, 110));
        jPanelFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelFuncionariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelFuncionariosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelFuncionariosMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img_funcionario.png"))); // NOI18N

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Funcionarios");

        javax.swing.GroupLayout jPanelFuncionariosLayout = new javax.swing.GroupLayout(jPanelFuncionarios);
        jPanelFuncionarios.setLayout(jPanelFuncionariosLayout);
        jPanelFuncionariosLayout.setHorizontalGroup(
            jPanelFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFuncionariosLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(13, 13, 13))
            .addGroup(jPanelFuncionariosLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFuncionariosLayout.setVerticalGroup(
            jPanelFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFuncionariosLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jPanel2.add(jPanelFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 170, 110));
        jPanel2.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 260, 10));
        jPanel2.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 260, 30));
        jPanel2.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 260, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelAlunosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAlunosMouseEntered
        // TODO add your handling code here:
        setColor(jPanelAlunos);
    }//GEN-LAST:event_jPanelAlunosMouseEntered

    private void jPanelAlunosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAlunosMouseExited
        // TODO add your handling code here:
        resetColor(jPanelAlunos);
    }//GEN-LAST:event_jPanelAlunosMouseExited

    private void jPanelVisitantesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelVisitantesMouseEntered
        // TODO add your handling code here:
        setColor(jPanelVisitantes);
    }//GEN-LAST:event_jPanelVisitantesMouseEntered

    private void jPanelVisitantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelVisitantesMouseExited
        // TODO add your handling code here:
        resetColor(jPanelVisitantes);
    }//GEN-LAST:event_jPanelVisitantesMouseExited

    private void jPanelFuncionariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFuncionariosMouseEntered
        // TODO add your handling code here:
        setColor(jPanelFuncionarios);
    }//GEN-LAST:event_jPanelFuncionariosMouseEntered

    private void jPanelFuncionariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFuncionariosMouseExited
        // TODO add your handling code here:
        resetColor(jPanelFuncionarios);
    }//GEN-LAST:event_jPanelFuncionariosMouseExited

    private void jPanelPortariaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPortariaMouseEntered
        // TODO add your handling code here:
        setColor(jPanelPortaria);
    }//GEN-LAST:event_jPanelPortariaMouseEntered

    private void jPanelPortariaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPortariaMouseExited
        // TODO add your handling code here:
        resetColor(jPanelPortaria);
    }//GEN-LAST:event_jPanelPortariaMouseExited

    private void jPanelVisitantesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelVisitantesMousePressed
        // TODO add your handling code here:
         new TelaCadastroVisitantes().show();//
    }//GEN-LAST:event_jPanelVisitantesMousePressed

    private void jPanelFuncionariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelFuncionariosMousePressed
        // TODO add your handling code here:
         new TelaCadastroFuncionario().show();//
    }//GEN-LAST:event_jPanelFuncionariosMousePressed

    private void jPanelPortariaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPortariaMousePressed
        // TODO add your handling code here:
        new TelaCadastroPortaria().show();
    }//GEN-LAST:event_jPanelPortariaMousePressed

    private void jLfecharMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLfecharMousePressed
        // TODO add your handling code here:
        new TelaMenu().show();
    }//GEN-LAST:event_jLfecharMousePressed

    private void jLfecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLfecharMouseClicked

    }//GEN-LAST:event_jLfecharMouseClicked

    private void jLfechar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLfechar1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLfechar1MouseClicked

    private void vCampoAlunoFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vCampoAlunoFemActionPerformed
        if (vCampoAlunoMasc.isSelected() || vCampoAlunoOut.isSelected()){
            vCampoAlunoMasc.setSelected(false);
            vCampoAlunoOut.setSelected(false);

        }
    }//GEN-LAST:event_vCampoAlunoFemActionPerformed

    private void vCampoAlunoMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vCampoAlunoMascActionPerformed
        if (vCampoAlunoOut.isSelected() || vCampoAlunoFem.isSelected()){
            vCampoAlunoOut.setSelected(false);
            vCampoAlunoFem.setSelected(false);

        }
    }//GEN-LAST:event_vCampoAlunoMascActionPerformed

    private void vCampoAlunoOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vCampoAlunoOutActionPerformed
        if (vCampoAlunoMasc.isSelected() || vCampoAlunoFem.isSelected()){
            vCampoAlunoMasc.setSelected(false);
            vCampoAlunoFem.setSelected(false);

        }
    }//GEN-LAST:event_vCampoAlunoOutActionPerformed

    private void vCelularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vCelularMouseClicked
        vCelular.setText("");
    }//GEN-LAST:event_vCelularMouseClicked

    private void vRgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vRgMouseClicked
        vRg.setText("");
    }//GEN-LAST:event_vRgMouseClicked

    private void vMatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vMatriculaMouseClicked
        vMatricula.setText("");
    }//GEN-LAST:event_vMatriculaMouseClicked

    private void vDataNascimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vDataNascimentoMouseClicked
        vDataNascimento.setText("");
    }//GEN-LAST:event_vDataNascimentoMouseClicked

    private void jbLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbLimparMouseClicked
        // TODO add your handling code here:
        vRg.setText("");
        vBairro.setText("");
        vCelular.setText("");
        vCep.setText("");
        vCidade.setText("");
        vRg.setText("");
        vDataNascimento.setText("");
        vEmail.setText("");
        vMatricula.setText("");
        vRg.setText("");
        vNumero.setText("");
        vRg.setText("");
        vRua.setText("");
        vCelular.setText("");
        vUf.setText("");
    }//GEN-LAST:event_jbLimparMouseClicked

    private void jbCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCadastrarMouseClicked
        // TODO add your handling code here:
               // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("apportariasoloPU");
        PessoaGeralJpaController pessoaJpaController = new PessoaGeralJpaController(emf);
        AlunoJpaController alunoJpaController = new AlunoJpaController(emf);
        SetorJpaController setorJpaController = new SetorJpaController(emf);
        CursoJpaController cursoJpaController = new CursoJpaController(emf);
        List<PessoaGeral> listaPessoa = new ArrayList<>();
        List<Curso> listaCursos = new ArrayList<>();
        //listaPessoa = pessoaJpaController.listaUltimouatro();
        System.out.println("");
        Curso curso = new Curso();
        Setor setor = new Setor();
        List<Setor> listaSetor = new ArrayList<>();
        int idSetor = 0;
        String idSetorPego = null;
        String idCursoPego = null;
        // for (PessoaGeral pessoa : listaPessoa) {
        // System.out.println(pessoa.toString());
        //}
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        //criando o objeto, importara dados do modelo pessoa
        String msg = "";
        int erro = 0;
        int idCurso=0;
        //String sexo = (String) vSexo.getSelectedItem();
        //Integer fkpg=0;
        //DefaultTableModel TempTabela = new DefaultTableModel(colunas,0);
        PessoaGeral pessoa = new PessoaGeral();
        //fkpg=pessoa.getIdPessoaGeral();
        pessoa.setNome(vNome.getText());
        pessoa.setCpf(vCpf.getText());
        pessoa.setEmail(vEmail.getText());
        pessoa.setCelular(vCelular.getText());
        pessoa.setBairro(vBairro.getText());
        pessoa.setNumero(vNumero.getText());
        pessoa.setRg(vRg.getText());
        pessoa.setTelefone(vCelular.getText());
        pessoa.setCep(vCep.getText());
        pessoa.setEndereco(vRua.getText());
        pessoa.setCidade(vCidade.getText());
        pessoa.setUf(vUf.getText());
        String setorN = (String) vSetor.getSelectedItem();
        String cursoN = (String) vCurso.getSelectedItem();
        //pessoa.setSexo(vSexo.setSelectedItem(ABORT));

        Aluno aluno = new Aluno();
        aluno.setMatricula(vMatricula.getText());

        if (pessoa.getNome().isEmpty()) {
            msg = msg + "\n Nome é obrigatorio";
            erro++;
        }
        if (pessoa.getCpf().isEmpty()) {
            msg = msg + "\n CPF é obrigatorio";
            erro++;
        }
        if(vCampoAlunoMasc.isSelected()){
            pessoa.setSexo(1);
        }
        if(vCampoAlunoFem.isSelected()){
            pessoa.setSexo(2);
        }
        if(vCampoAlunoOut.isSelected()){
            pessoa.setSexo(3);
        }
        try {

            listaSetor = setorJpaController.listaSetor(setorN);
            for (int i = 0; i <= listaPessoa.size(); i++) {
                idSetorPego = String.valueOf(listaSetor.get(i));
                idSetor = Integer.valueOf(idSetorPego);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        aluno.setIdSetorFk(new Setor());
        setor = setorJpaController.findSetor(idSetor);
        aluno.setIdSetorFk(setor);

        try {

            listaCursos = cursoJpaController.listaCursos(cursoN);
            for (int i = 0; i <= listaCursos.size(); i++) {
                idCursoPego = String.valueOf(listaCursos.get(i));
                idCurso = Integer.valueOf(idCursoPego);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        aluno.setIdCursoFk(new Curso());
        curso = cursoJpaController.findCurso(idCurso);
        aluno.setIdCursoFk(curso);

        if (erro > 0) {
            JOptionPane.showMessageDialog(null, msg);
        } else {
            try {
                JOptionPane.showMessageDialog(null, msg);
                if (!vDataNascimento.getText().isEmpty()) {
                    pessoa.setDatadenascimento((Date) dateFormat.parse(vDataNascimento.getText()));
                }

                pessoaJpaController.create(pessoa);
                aluno.setIdPessoaGeralFk(pessoa);
                alunoJpaController.create(aluno);
                JOptionPane.showMessageDialog(null, "Aluno Cadastrado Com Sucesso");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
        
    }//GEN-LAST:event_jbCadastrarMouseClicked

    private void vCepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vCepMouseClicked
        // TODO add your handling code here:
        vCep.setText("");
    }//GEN-LAST:event_vCepMouseClicked

    private void vTelefoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vTelefoneMouseClicked
        // TODO add your handling code here:
        vTelefone.setText("");
    }//GEN-LAST:event_vTelefoneMouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        //int x = evt.getXOnScreen();
        //int y = evt.getYOnScreen();
        //this.setLocation(x - xx, y - xy);
        
    }//GEN-LAST:event_jPanel1MouseDragged
        //int xx,xy; 
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
                                         
        //xx = evt.getX();
        //xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void vNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vNomeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_vNomeMouseClicked

    private void vCpfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vCpfMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_vCpfMouseClicked

    public void setColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(11,100,145));
 }
 
 public void resetColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(0,51,102));
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cjcidad;
    private javax.swing.JLabel jCep;
    private javax.swing.JLabel jClular;
    private javax.swing.JLabel jCpf;
    private javax.swing.JLabel jCur;
    private javax.swing.JLabel jDt;
    private javax.swing.JLabel jEmail;
    private javax.swing.JLabel jGen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLfechar;
    private javax.swing.JLabel jLfechar1;
    private javax.swing.JLabel jMatri;
    private javax.swing.JLabel jNome;
    private javax.swing.JLabel jNumCasa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAlunos;
    private javax.swing.JPanel jPanelFuncionarios;
    private javax.swing.JPanel jPanelPortaria;
    private javax.swing.JPanel jPanelVisitantes;
    private javax.swing.JLabel jRg;
    private javax.swing.JLabel jRua;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel jSetor;
    private javax.swing.JLabel jTelef;
    private javax.swing.JLabel jUf;
    private javax.swing.JLabel jairro;
    private javax.swing.JLabel jbCadastra;
    private javax.swing.JPanel jbCadastrar;
    private javax.swing.JLabel jbLimpa;
    private javax.swing.JPanel jbLimpar;
    private javax.swing.JTextField vBairro;
    private javax.swing.JCheckBox vCampoAlunoFem;
    private javax.swing.JCheckBox vCampoAlunoMasc;
    private javax.swing.JCheckBox vCampoAlunoOut;
    private javax.swing.JFormattedTextField vCelular;
    private javax.swing.JFormattedTextField vCep;
    private javax.swing.JTextField vCidade;
    private javax.swing.JTextField vCpf;
    private javax.swing.JComboBox<String> vCurso;
    private javax.swing.JFormattedTextField vDataNascimento;
    private javax.swing.JTextField vEmail;
    private javax.swing.JFormattedTextField vMatricula;
    private javax.swing.JTextField vNome;
    private javax.swing.JTextField vNumero;
    private javax.swing.JTextField vRg;
    private javax.swing.JTextField vRua;
    private javax.swing.JComboBox<String> vSetor;
    private javax.swing.JFormattedTextField vTelefone;
    private javax.swing.JTextField vUf;
    // End of variables declaration//GEN-END:variables
}
