/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author HAVING
 */
public class TelaCadastroUser extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroUser
     */
    public TelaCadastroUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelLogo = new javax.swing.JPanel();
        painelLoguin = new javax.swing.JPanel();
        vConta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botaoEntrar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        vSenha1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        vSenha2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        vemail1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLfechar = new javax.swing.JLabel();
        jLfechar4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 540));
        setUndecorated(true);

        painelLogo.setBackground(new java.awt.Color(0, 51, 102));
        painelLogo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                painelLogoMouseDragged(evt);
            }
        });
        painelLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                painelLogoMousePressed(evt);
            }
        });

        painelLoguin.setBackground(new java.awt.Color(204, 204, 204));
        painelLoguin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vConta.setBackground(new java.awt.Color(204, 204, 204));
        vConta.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        vConta.setForeground(new java.awt.Color(102, 102, 102));
        vConta.setText("Digite seu usuario:");
        vConta.setBorder(null);
        vConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vContaMouseClicked(evt);
            }
        });
        painelLoguin.add(vConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 276, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img_login.png"))); // NOI18N
        painelLoguin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 100, 110));

        jLabel2.setBackground(new java.awt.Color(0, 51, 153));
        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("CONTA");
        painelLoguin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 70, 29));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img_user.png"))); // NOI18N
        painelLoguin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 20, 34));

        jSeparator1.setBackground(new java.awt.Color(0, 51, 102));
        jSeparator1.setForeground(new java.awt.Color(0, 51, 102));
        painelLoguin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 290, 10));

        jLabel4.setBackground(new java.awt.Color(0, 51, 153));
        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("SENHA");
        painelLoguin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 70, 29));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img_senha.png"))); // NOI18N
        painelLoguin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 20, 34));

        botaoEntrar.setBackground(new java.awt.Color(0, 51, 102));
        botaoEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botaoEntrarMousePressed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CADASTRAR");

        javax.swing.GroupLayout botaoEntrarLayout = new javax.swing.GroupLayout(botaoEntrar);
        botaoEntrar.setLayout(botaoEntrarLayout);
        botaoEntrarLayout.setHorizontalGroup(
            botaoEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoEntrarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        botaoEntrarLayout.setVerticalGroup(
            botaoEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoEntrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelLoguin.add(botaoEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 110, 30));

        jSeparator5.setBackground(new java.awt.Color(0, 51, 102));
        jSeparator5.setForeground(new java.awt.Color(0, 51, 102));
        painelLoguin.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 290, 20));

        vSenha1.setBackground(new java.awt.Color(204, 204, 204));
        vSenha1.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        vSenha1.setForeground(new java.awt.Color(102, 102, 102));
        vSenha1.setText("Digite sua senha:");
        vSenha1.setBorder(null);
        vSenha1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vSenha1MouseClicked(evt);
            }
        });
        painelLoguin.add(vSenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 270, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img_senha.png"))); // NOI18N
        painelLoguin.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 20, 34));

        jLabel12.setBackground(new java.awt.Color(0, 51, 153));
        jLabel12.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 102));
        jLabel12.setText("CONFIRME A SENHA ");
        painelLoguin.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 140, -1));

        jSeparator6.setBackground(new java.awt.Color(0, 51, 102));
        jSeparator6.setForeground(new java.awt.Color(0, 51, 102));
        painelLoguin.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 290, 20));

        vSenha2.setBackground(new java.awt.Color(204, 204, 204));
        vSenha2.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        vSenha2.setForeground(new java.awt.Color(102, 102, 102));
        vSenha2.setText("Digite a senha novamente:");
        vSenha2.setBorder(null);
        vSenha2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vSenha2MouseClicked(evt);
            }
        });
        painelLoguin.add(vSenha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 270, 20));

        jLabel7.setBackground(new java.awt.Color(0, 51, 153));
        jLabel7.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("E-MAIL");
        painelLoguin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 70, 29));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img_user.png"))); // NOI18N
        painelLoguin.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 20, 34));

        vemail1.setBackground(new java.awt.Color(204, 204, 204));
        vemail1.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        vemail1.setForeground(new java.awt.Color(102, 102, 102));
        vemail1.setText("Digite seu E-mail:");
        vemail1.setBorder(null);
        vemail1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vemail1MouseClicked(evt);
            }
        });
        painelLoguin.add(vemail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 276, 20));

        jSeparator2.setBackground(new java.awt.Color(0, 51, 102));
        jSeparator2.setForeground(new java.awt.Color(0, 51, 102));
        painelLoguin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 290, 10));

        jLfechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img_home1.png"))); // NOI18N
        jLfechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLfecharMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLfecharMousePressed(evt);
            }
        });

        jLfechar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img_fexar1.png"))); // NOI18N
        jLfechar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLfechar4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelLogoLayout = new javax.swing.GroupLayout(painelLogo);
        painelLogo.setLayout(painelLogoLayout);
        painelLogoLayout.setHorizontalGroup(
            painelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLogoLayout.createSequentialGroup()
                .addContainerGap(332, Short.MAX_VALUE)
                .addComponent(painelLoguin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259)
                .addComponent(jLfechar)
                .addGap(6, 6, 6)
                .addComponent(jLfechar4)
                .addContainerGap())
        );
        painelLogoLayout.setVerticalGroup(
            painelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLogoLayout.createSequentialGroup()
                .addGroup(painelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLogoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLfechar4)
                            .addComponent(jLfechar)))
                    .addGroup(painelLogoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(painelLoguin, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLfecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLfecharMouseClicked

    }//GEN-LAST:event_jLfecharMouseClicked

    private void jLfecharMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLfecharMousePressed
        // TODO add your handling code here:
        new Tlogin().show();
    }//GEN-LAST:event_jLfecharMousePressed

    private void jLfechar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLfechar4MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLfechar4MouseClicked

    private void vemail1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vemail1MouseClicked
        // TODO add your handling code here:
        vemail1.setText("");
    }//GEN-LAST:event_vemail1MouseClicked

    private void vSenha2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vSenha2MouseClicked
        // TODO add your handling code here:
        vSenha2.setText("");
    }//GEN-LAST:event_vSenha2MouseClicked

    private void vSenha1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vSenha1MouseClicked
        // TODO add your handling code here:
        vSenha1.setText("");
    }//GEN-LAST:event_vSenha1MouseClicked

    private void botaoEntrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEntrarMousePressed
        new Tlogin().show();// TODO add your handling code here:
    }//GEN-LAST:event_botaoEntrarMousePressed

    private void vContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vContaMouseClicked
        vConta.setText("");
    }//GEN-LAST:event_vContaMouseClicked

    private void painelLogoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelLogoMouseDragged
        // TODO add your handling code here:
        //int x = evt.getXOnScreen();
        //int y = evt.getYOnScreen();
        //this.setLocation(x - xx, y - xy);
        
    }//GEN-LAST:event_painelLogoMouseDragged
    //int xx,xy;
    private void painelLogoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelLogoMousePressed
        // TODO add your handling code here:
        //xx = evt.getX();
        //xy = evt.getY();
    }//GEN-LAST:event_painelLogoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botaoEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLfechar;
    private javax.swing.JLabel jLfechar4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPanel painelLogo;
    private javax.swing.JPanel painelLoguin;
    private javax.swing.JTextField vConta;
    private javax.swing.JTextField vSenha1;
    private javax.swing.JTextField vSenha2;
    private javax.swing.JTextField vemail1;
    // End of variables declaration//GEN-END:variables
}
