/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import br.edu.uerr.appportariasolo.controler.PessoaGeralJpaController;
import br.edu.uerr.appportariasolo.controler.PortariaJpaController;
import br.edu.uerr.appportariasolo.modelo.PessoaGeral;
import br.edu.uerr.appportariasolo.modelo.Portaria;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author DevSilva
 */
public class TelaCadastroPortaria extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroPortaria
     */
    public TelaCadastroPortaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jRg = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jCpf = new javax.swing.JLabel();
        vbuscaNome = new javax.swing.JTextField();
        jClular = new javax.swing.JLabel();
        jSeparator24 = new javax.swing.JSeparator();
        jbEnviar = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        vLimpar = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jGen = new javax.swing.JLabel();
        jNome = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        vCampoAlunoOut = new javax.swing.JCheckBox();
        vCampoAlunoMasc = new javax.swing.JCheckBox();
        vCampoAlunoFem = new javax.swing.JCheckBox();
        jSeparator10 = new javax.swing.JSeparator();
        jLfechar1 = new javax.swing.JLabel();
        jLfechar = new javax.swing.JLabel();
        jGen1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        bvDataHora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator25 = new javax.swing.JSeparator();
        vDataHora = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        vBuscaTipoPessoa = new javax.swing.JTextField();
        jNome1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jCpf1 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        vBuscaRg = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        vDescricao = new javax.swing.JTextArea();
        jSeparator26 = new javax.swing.JSeparator();
        vNomePessoaPortaria = new javax.swing.JTextField();
        vCpfPessoaPortaria = new javax.swing.JTextField();
        vBuscaCelular = new javax.swing.JTextField();
        vBuscaCpf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 500, 10));

        jRg.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jRg.setForeground(new java.awt.Color(0, 51, 102));
        jRg.setText("RG:");
        jPanel1.add(jRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 50, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 130, 10));

        jCpf.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jCpf.setForeground(new java.awt.Color(0, 51, 102));
        jCpf.setText("CPF:");
        jPanel1.add(jCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 50, -1));

        vbuscaNome.setBackground(new java.awt.Color(204, 204, 204));
        vbuscaNome.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vbuscaNome.setForeground(new java.awt.Color(153, 153, 153));
        vbuscaNome.setText("Digite o nome comleto");
        vbuscaNome.setBorder(null);
        vbuscaNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vbuscaNomeMouseClicked(evt);
            }
        });
        vbuscaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vbuscaNomeActionPerformed(evt);
            }
        });
        jPanel1.add(vbuscaNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 500, -1));

        jClular.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jClular.setForeground(new java.awt.Color(0, 51, 102));
        jClular.setText("Celular:");
        jPanel1.add(jClular, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 60, -1));
        jPanel1.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 150, 10));

        jbEnviar.setBackground(new java.awt.Color(0, 51, 102));
        jbEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbEnviarMouseClicked(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("CADASTRAR");

        javax.swing.GroupLayout jbEnviarLayout = new javax.swing.GroupLayout(jbEnviar);
        jbEnviar.setLayout(jbEnviarLayout);
        jbEnviarLayout.setHorizontalGroup(
            jbEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbEnviarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel14)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jbEnviarLayout.setVerticalGroup(
            jbEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jbEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, 120, 30));

        vLimpar.setBackground(new java.awt.Color(0, 51, 102));
        vLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vLimparMouseClicked(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("LIMPAR");

        javax.swing.GroupLayout vLimparLayout = new javax.swing.GroupLayout(vLimpar);
        vLimpar.setLayout(vLimparLayout);
        vLimparLayout.setHorizontalGroup(
            vLimparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vLimparLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel17)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        vLimparLayout.setVerticalGroup(
            vLimparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vLimparLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(vLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        jGen.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jGen.setForeground(new java.awt.Color(0, 51, 102));
        jGen.setText("Género:");
        jPanel1.add(jGen, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 70, -1));

        jNome.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jNome.setForeground(new java.awt.Color(0, 51, 102));
        jNome.setText("Nome:");
        jPanel1.add(jNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 50, -1));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 120, 10));

        vCampoAlunoOut.setBackground(new java.awt.Color(204, 204, 204));
        vCampoAlunoOut.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vCampoAlunoOut.setForeground(new java.awt.Color(153, 153, 153));
        vCampoAlunoOut.setText("Outro");
        vCampoAlunoOut.setBorder(null);
        vCampoAlunoOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vCampoAlunoOutActionPerformed(evt);
            }
        });
        jPanel1.add(vCampoAlunoOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));

        vCampoAlunoMasc.setBackground(new java.awt.Color(204, 204, 204));
        vCampoAlunoMasc.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vCampoAlunoMasc.setForeground(new java.awt.Color(153, 153, 153));
        vCampoAlunoMasc.setText("Masculino");
        vCampoAlunoMasc.setBorder(null);
        vCampoAlunoMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vCampoAlunoMascActionPerformed(evt);
            }
        });
        jPanel1.add(vCampoAlunoMasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        vCampoAlunoFem.setBackground(new java.awt.Color(204, 204, 204));
        vCampoAlunoFem.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vCampoAlunoFem.setForeground(new java.awt.Color(153, 153, 153));
        vCampoAlunoFem.setText("Feminino");
        vCampoAlunoFem.setBorder(null);
        vCampoAlunoFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vCampoAlunoFemActionPerformed(evt);
            }
        });
        jPanel1.add(vCampoAlunoFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 290, 10));

        jLfechar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img_fexar.png"))); // NOI18N
        jLfechar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLfechar1MouseClicked(evt);
            }
        });
        jPanel1.add(jLfechar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, 30));

        jLfechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img_home.png"))); // NOI18N
        jLfechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLfecharMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLfecharMousePressed(evt);
            }
        });
        jPanel1.add(jLfechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, 30));

        jGen1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jGen1.setForeground(new java.awt.Color(0, 51, 102));
        jGen1.setText("Tipo:");
        jPanel1.add(jGen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 40, -1));

        jPanel6.setBackground(new java.awt.Color(0, 51, 102));

        bvDataHora.setBackground(new java.awt.Color(255, 255, 255));
        bvDataHora.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        bvDataHora.setForeground(new java.awt.Color(255, 255, 255));
        bvDataHora.setText("DATA E HORA ATUAL");
        bvDataHora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bvDataHoraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(bvDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bvDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 150, -1));

        jLabel1.setForeground(new java.awt.Color(109, 109, 109));
        jLabel1.setText("*Descreva em poucas palavras os motivos da entrada! ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));

        jLabel2.setForeground(new java.awt.Color(109, 109, 109));
        jLabel2.setText("inseririr a data e hora atua!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, -1, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 680, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 102));
        jLabel16.setText("BUSCAR UMA PORTARIA ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 40));

        jLabel3.setForeground(new java.awt.Color(109, 109, 109));
        jLabel3.setText("*Clique no botão para ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, -1, -1));
        jPanel1.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 170, 10));

        vDataHora.setBackground(new java.awt.Color(255, 255, 255));
        vDataHora.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        vDataHora.setForeground(new java.awt.Color(0, 51, 102));
        vDataHora.setText(" dd/mm/aaaa  hh:mm");
        jPanel1.add(vDataHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, -1, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 500, 10));

        vBuscaTipoPessoa.setBackground(new java.awt.Color(204, 204, 204));
        vBuscaTipoPessoa.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vBuscaTipoPessoa.setForeground(new java.awt.Color(153, 153, 153));
        vBuscaTipoPessoa.setBorder(null);
        vBuscaTipoPessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vBuscaTipoPessoaMouseClicked(evt);
            }
        });
        vBuscaTipoPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vBuscaTipoPessoaActionPerformed(evt);
            }
        });
        jPanel1.add(vBuscaTipoPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 130, -1));

        jNome1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jNome1.setForeground(new java.awt.Color(0, 51, 102));
        jNome1.setText("Nome:");
        jPanel1.add(jNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, -1));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 102));
        jLabel18.setText("CADASTRO DE PORTARIA");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 220, 40));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 680, -1));

        jCpf1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jCpf1.setForeground(new java.awt.Color(0, 51, 102));
        jCpf1.setText("CPF:");
        jPanel1.add(jCpf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 50, -1));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 120, 10));

        jPanel8.setBackground(new java.awt.Color(0, 51, 102));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
        });

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("PESQUISAR");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel21)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 120, 110, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 680, -1));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 51, 102));
        jLabel23.setText("DESCRIÇÃO");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 110, 40));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 130, 10));

        vBuscaRg.setBackground(new java.awt.Color(204, 204, 204));
        vBuscaRg.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vBuscaRg.setForeground(new java.awt.Color(153, 153, 153));
        vBuscaRg.setBorder(null);
        vBuscaRg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vBuscaRgMouseClicked(evt);
            }
        });
        vBuscaRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vBuscaRgActionPerformed(evt);
            }
        });
        jPanel1.add(vBuscaRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 110, -1));

        vDescricao.setBackground(new java.awt.Color(204, 204, 204));
        vDescricao.setColumns(20);
        vDescricao.setRows(5);
        vDescricao.setBorder(null);
        jScrollPane1.setViewportView(vDescricao);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 450, 90));
        jPanel1.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 110, 10));

        vNomePessoaPortaria.setBackground(new java.awt.Color(204, 204, 204));
        vNomePessoaPortaria.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vNomePessoaPortaria.setForeground(new java.awt.Color(153, 153, 153));
        vNomePessoaPortaria.setText("Digite o nome comleto");
        vNomePessoaPortaria.setBorder(null);
        vNomePessoaPortaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vNomePessoaPortariaMouseClicked(evt);
            }
        });
        jPanel1.add(vNomePessoaPortaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 500, -1));

        vCpfPessoaPortaria.setBackground(new java.awt.Color(204, 204, 204));
        vCpfPessoaPortaria.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vCpfPessoaPortaria.setForeground(new java.awt.Color(153, 153, 153));
        vCpfPessoaPortaria.setBorder(null);
        vCpfPessoaPortaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vCpfPessoaPortariaMouseClicked(evt);
            }
        });
        vCpfPessoaPortaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vCpfPessoaPortariaActionPerformed(evt);
            }
        });
        jPanel1.add(vCpfPessoaPortaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 110, -1));

        vBuscaCelular.setBackground(new java.awt.Color(204, 204, 204));
        vBuscaCelular.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vBuscaCelular.setForeground(new java.awt.Color(153, 153, 153));
        vBuscaCelular.setBorder(null);
        vBuscaCelular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vBuscaCelularMouseClicked(evt);
            }
        });
        vBuscaCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vBuscaCelularActionPerformed(evt);
            }
        });
        jPanel1.add(vBuscaCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 110, -1));

        vBuscaCpf.setBackground(new java.awt.Color(204, 204, 204));
        vBuscaCpf.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        vBuscaCpf.setForeground(new java.awt.Color(153, 153, 153));
        vBuscaCpf.setBorder(null);
        vBuscaCpf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vBuscaCpfMouseClicked(evt);
            }
        });
        vBuscaCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vBuscaCpfActionPerformed(evt);
            }
        });
        jPanel1.add(vBuscaCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(680, 540));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLfecharMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLfecharMousePressed
        // TODO add your handling code here:
        new TelaMenu().show();
    }//GEN-LAST:event_jLfecharMousePressed

    private void jLfecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLfecharMouseClicked

    }//GEN-LAST:event_jLfecharMouseClicked

    private void jLfechar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLfechar1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLfechar1MouseClicked

    private void vCampoAlunoFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vCampoAlunoFemActionPerformed
        if (vCampoAlunoMasc.isSelected() || vCampoAlunoOut.isSelected()) {
            vCampoAlunoMasc.setSelected(false);
            vCampoAlunoOut.setSelected(false);

        }
    }//GEN-LAST:event_vCampoAlunoFemActionPerformed

    private void vCampoAlunoMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vCampoAlunoMascActionPerformed
        if (vCampoAlunoOut.isSelected() || vCampoAlunoFem.isSelected()) {
            vCampoAlunoOut.setSelected(false);
            vCampoAlunoFem.setSelected(false);

        }
    }//GEN-LAST:event_vCampoAlunoMascActionPerformed

    private void vCampoAlunoOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vCampoAlunoOutActionPerformed
        if (vCampoAlunoMasc.isSelected() || vCampoAlunoFem.isSelected()) {
            vCampoAlunoMasc.setSelected(false);
            vCampoAlunoFem.setSelected(false);

        }
    }//GEN-LAST:event_vCampoAlunoOutActionPerformed

    private void vbuscaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vbuscaNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vbuscaNomeActionPerformed

    private void vbuscaNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vbuscaNomeMouseClicked
        vbuscaNome.setText("");
    }//GEN-LAST:event_vbuscaNomeMouseClicked

    private void vBuscaTipoPessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vBuscaTipoPessoaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_vBuscaTipoPessoaMouseClicked

    private void vBuscaTipoPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vBuscaTipoPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vBuscaTipoPessoaActionPerformed

    private void vBuscaRgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vBuscaRgMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_vBuscaRgMouseClicked

    private void vBuscaRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vBuscaRgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vBuscaRgActionPerformed

    private void vNomePessoaPortariaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vNomePessoaPortariaMouseClicked
         vNomePessoaPortaria.setText("");
    }//GEN-LAST:event_vNomePessoaPortariaMouseClicked

    private void vCpfPessoaPortariaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vCpfPessoaPortariaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_vCpfPessoaPortariaMouseClicked

    private void vCpfPessoaPortariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vCpfPessoaPortariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vCpfPessoaPortariaActionPerformed

    private void vBuscaCelularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vBuscaCelularMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_vBuscaCelularMouseClicked

    private void vBuscaCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vBuscaCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vBuscaCelularActionPerformed

    private void vBuscaCpfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vBuscaCpfMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_vBuscaCpfMouseClicked

    private void vBuscaCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vBuscaCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vBuscaCpfActionPerformed

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("apportariasoloPU");
        PessoaGeralJpaController pessoaGeralJpaController = new PessoaGeralJpaController(emf);
        List<PessoaGeral> listaPessoa = new ArrayList<PessoaGeral>();
        PessoaGeral pessoa = new PessoaGeral();
        String nomePBusca = String.valueOf(vNomePessoaPortaria.getText());
        String cpfPBusca = (String) vCpfPessoaPortaria.getText();
        String nomeDbuscado = null;
        vCampoAlunoOut.setSelected(false);
        vCampoAlunoMasc.setSelected(false);
        vCampoAlunoFem.setSelected(false);
        int sexoDBuscado = 0;
        try {

            listaPessoa = pessoaGeralJpaController.listaNomePessoa(nomePBusca, cpfPBusca);
            for (int i = 0; i <= listaPessoa.size(); i++) {
                nomeDbuscado = String.valueOf(listaPessoa.get(i));
                vbuscaNome.setText(nomeDbuscado);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        try {

            listaPessoa = pessoaGeralJpaController.listaCpfPessoa(nomePBusca, cpfPBusca);
            for (int i = 0; i <= listaPessoa.size(); i++) {
                nomeDbuscado = String.valueOf(listaPessoa.get(i));
                vBuscaCpf.setText(nomeDbuscado);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        try {

            listaPessoa = pessoaGeralJpaController.listaRgPessoa(nomePBusca, cpfPBusca);
            for (int i = 0; i <= listaPessoa.size(); i++) {
                nomeDbuscado = String.valueOf(listaPessoa.get(i));
                vBuscaRg.setText(nomeDbuscado);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        try {

            listaPessoa = pessoaGeralJpaController.listaSexoPessoa(nomePBusca, cpfPBusca);
            for (int i = 0; i <= listaPessoa.size(); i++) {
                nomeDbuscado = String.valueOf(listaPessoa.get(i));
                sexoDBuscado = Integer.valueOf(nomeDbuscado);
                /*
                if (sexoDBuscado == 1) {
                    vBuscaSexo.setText("Masculino");
                } else {
                    vBuscaSexo.setText("Feminino");
                }
                 */
                if (sexoDBuscado == 1) {
                    vCampoAlunoMasc.setSelected(true);
                }
                if (sexoDBuscado == 2) {
                    vCampoAlunoFem.setSelected(true);
                }
                if (sexoDBuscado == 3) {
                    vCampoAlunoOut.setSelected(true);
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        try {

            listaPessoa = pessoaGeralJpaController.listaCelularPessoa(nomePBusca, cpfPBusca);
            for (int i = 0; i <= listaPessoa.size(); i++) {
                nomeDbuscado = String.valueOf(listaPessoa.get(i));
                vBuscaCelular.setText(nomeDbuscado);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        try {

            listaPessoa = pessoaGeralJpaController.listaTipoPessoaFunc(nomePBusca, cpfPBusca);
            for (int i = 0; i <= listaPessoa.size(); i++) {
                nomeDbuscado = String.valueOf(listaPessoa.get(i));
                if (Objects.equals(nomeDbuscado, nomePBusca)) {
                    vBuscaTipoPessoa.setText("Funcionario");
                } else {
                    vBuscaTipoPessoa.setText(nomePBusca);
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        try {

            listaPessoa = pessoaGeralJpaController.listaTipoPessoaAlun(nomePBusca, cpfPBusca);
            for (int i = 0; i <= listaPessoa.size(); i++) {
                nomeDbuscado = String.valueOf(listaPessoa.get(i));
                if (Objects.equals(nomeDbuscado, nomePBusca)) {
                    vBuscaTipoPessoa.setText("Aluno");
                } else {
                    vBuscaTipoPessoa.setText(nomePBusca);
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        try {

            listaPessoa = pessoaGeralJpaController.listaTipoPessoaVis(nomePBusca, cpfPBusca);
            for (int i = 0; i <= listaPessoa.size(); i++) {
                nomeDbuscado = String.valueOf(listaPessoa.get(i));
                if (Objects.equals(nomeDbuscado, nomePBusca)) {
                    vBuscaTipoPessoa.setText("Vizitante");
                } else {
                    vBuscaTipoPessoa.setText(nomePBusca);
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }


    }//GEN-LAST:event_jPanel8MouseClicked

    private void vLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vLimparMouseClicked
        // TODO add your handling code here:
        vBuscaCelular.setText("");
        vBuscaCpf.setText("");
        vBuscaRg.setText("");
        vBuscaTipoPessoa.setText("");
        vCpfPessoaPortaria.setText("");
        vDataHora.setText("");
        vDescricao.setText("");
        vNomePessoaPortaria.setText("");
        vbuscaNome.setText("");
    }//GEN-LAST:event_vLimparMouseClicked

    private void bvDataHoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bvDataHoraMouseClicked
        // TODO add your handling code here:
        Date data = new Date();
        SimpleDateFormat date = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        String dataAgora = String.valueOf(date.format(data));
        System.out.println(date.format(data));
        vDataHora.setText(dataAgora);


    }//GEN-LAST:event_bvDataHoraMouseClicked

    private void jbEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbEnviarMouseClicked
        // TODO add your handling code here:
                EntityManagerFactory emf = Persistence.createEntityManagerFactory("apportariasoloPU");
        PessoaGeralJpaController pessoaGeralJpaController = new PessoaGeralJpaController(emf);
        PortariaJpaController portariaJpaController = new PortariaJpaController(emf);
        List<PessoaGeral> listaPessoa = new ArrayList<PessoaGeral>();
        PessoaGeral pessoa = new PessoaGeral();
        String nomePBusca = String.valueOf(vbuscaNome.getText());
        String cpfPBusca = (String) vBuscaCpf.getText();
        String nomeDbuscado = null;
        int sexoDBuscado = 0;
        System.out.println("");
        String idPessoaPego;
        int idPessoa = 0;

        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        Portaria portaria = new Portaria();
        //idPessoa = pessoa.getIdPessoaGeral();
        //portaria.setIdPessoaGeral(idPessoa);
        try {

            listaPessoa = pessoaGeralJpaController.listaIdPessoa(nomePBusca, cpfPBusca);
            for (int i = 0; i <= listaPessoa.size(); i++) {
                idPessoaPego = String.valueOf(listaPessoa.get(i));
                idPessoa = Integer.valueOf(idPessoaPego);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        portaria.setIdPessoaGeral(new PessoaGeral());
        pessoa = pessoaGeralJpaController.findPessoaGeral(idPessoa);
        portaria.setIdPessoaGeral(pessoa);;

        portaria.setDescricao(vDescricao.getText());
        try {
            if (!vDataHora.getText().isEmpty()) {
                portaria.setDataHoraEntrada((Date) dateFormat.parse(vDataHora.getText()));
            }
            portariaJpaController.create(portaria);
            JOptionPane.showMessageDialog(null, "Portaria Cadastrada Com Sucesso");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        
        
    }//GEN-LAST:event_jbEnviarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPortaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPortaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPortaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPortaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroPortaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bvDataHora;
    private javax.swing.JLabel jClular;
    private javax.swing.JLabel jCpf;
    private javax.swing.JLabel jCpf1;
    private javax.swing.JLabel jGen;
    private javax.swing.JLabel jGen1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLfechar;
    private javax.swing.JLabel jLfechar1;
    private javax.swing.JLabel jNome;
    private javax.swing.JLabel jNome1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel jRg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPanel jbEnviar;
    private javax.swing.JTextField vBuscaCelular;
    private javax.swing.JTextField vBuscaCpf;
    private javax.swing.JTextField vBuscaRg;
    private javax.swing.JTextField vBuscaTipoPessoa;
    private javax.swing.JCheckBox vCampoAlunoFem;
    private javax.swing.JCheckBox vCampoAlunoMasc;
    private javax.swing.JCheckBox vCampoAlunoOut;
    private javax.swing.JTextField vCpfPessoaPortaria;
    private javax.swing.JLabel vDataHora;
    private javax.swing.JTextArea vDescricao;
    private javax.swing.JPanel vLimpar;
    private javax.swing.JTextField vNomePessoaPortaria;
    private javax.swing.JTextField vbuscaNome;
    // End of variables declaration//GEN-END:variables
}
