/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import javax.swing.JOptionPane;

/**
 *
 * @author DevSilva
 */
public class Tlogin extends javax.swing.JFrame {

    /**
     * Creates new form Tlogin
     */
    public Tlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelLoguin = new javax.swing.JPanel();
        vConta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        vSenha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        botaoEntrar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLfechar = new javax.swing.JLabel();
        painelLogo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(960, 540));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelLoguin.setBackground(new java.awt.Color(204, 204, 204));
        painelLoguin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vConta.setBackground(new java.awt.Color(204, 204, 204));
        vConta.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        vConta.setForeground(new java.awt.Color(102, 102, 102));
        vConta.setText("Digite seu usuario:");
        vConta.setBorder(null);
        vConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vContaMouseClicked(evt);
            }
        });
        painelLoguin.add(vConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 188, 276, 34));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img_login.png"))); // NOI18N
        painelLoguin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 100, 110));

        jLabel2.setBackground(new java.awt.Color(0, 51, 153));
        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("USUARIO");
        painelLoguin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, 29));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img_user.png"))); // NOI18N
        painelLoguin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 188, 20, 34));

        jSeparator1.setBackground(new java.awt.Color(0, 51, 102));
        jSeparator1.setForeground(new java.awt.Color(0, 51, 102));
        painelLoguin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 228, 298, 10));

        vSenha.setBackground(new java.awt.Color(204, 204, 204));
        vSenha.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        vSenha.setForeground(new java.awt.Color(102, 102, 102));
        vSenha.setText("Digite sua senha:");
        vSenha.setBorder(null);
        vSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vSenhaMouseClicked(evt);
            }
        });
        vSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vSenhaActionPerformed(evt);
            }
        });
        painelLoguin.add(vSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 276, 34));

        jLabel4.setBackground(new java.awt.Color(0, 51, 153));
        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("SENHA");
        painelLoguin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 70, 29));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img_senha.png"))); // NOI18N
        painelLoguin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 20, 34));

        jSeparator2.setBackground(new java.awt.Color(0, 51, 102));
        jSeparator2.setForeground(new java.awt.Color(0, 51, 102));
        painelLoguin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 298, 10));

        botaoEntrar.setBackground(new java.awt.Color(0, 51, 102));
        botaoEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoEntrarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botaoEntrarMousePressed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ENTRAR");

        javax.swing.GroupLayout botaoEntrarLayout = new javax.swing.GroupLayout(botaoEntrar);
        botaoEntrar.setLayout(botaoEntrarLayout);
        botaoEntrarLayout.setHorizontalGroup(
            botaoEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botaoEntrarLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        botaoEntrarLayout.setVerticalGroup(
            botaoEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botaoEntrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelLoguin.add(botaoEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 170, 30));

        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("CLIQUE AQUI! ");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        painelLoguin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, 20));

        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("Não tem uma Conta? ");
        painelLoguin.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, 20));
        painelLoguin.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 70, 10));
        painelLoguin.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 70, 10));

        jLfechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Img_fexar.png"))); // NOI18N
        jLfechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLfecharMouseClicked(evt);
            }
        });
        painelLoguin.add(jLfechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 30, 30));

        getContentPane().add(painelLoguin, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 310, 540));

        painelLogo.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout painelLogoLayout = new javax.swing.GroupLayout(painelLogo);
        painelLogo.setLayout(painelLogoLayout);
        painelLogoLayout.setHorizontalGroup(
            painelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        painelLogoLayout.setVerticalGroup(
            painelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        getContentPane().add(painelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void vContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vContaMouseClicked
        vConta.setText("");
    }//GEN-LAST:event_vContaMouseClicked

    private void vSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vSenhaMouseClicked
        vSenha.setText(""); // TODO add your handling code here:
    }//GEN-LAST:event_vSenhaMouseClicked

    private void vSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vSenhaActionPerformed

    private void jLfecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLfecharMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLfecharMouseClicked

    private void botaoEntrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEntrarMousePressed
        String cont = null;
        String sen = null;
        cont=vConta.getText();
        sen=vSenha.getText();

        if (cont.equals("admin")&& sen.equals("admin")) {
            new TelaMenu().show();// TODO add your handling code here:
        } else {
            System.err.println(cont);
            System.err.println(sen);
            System.err.println("Nao deu");
            JOptionPane.showMessageDialog(null, "Usuario ou Senha Invalido");
        }
    }//GEN-LAST:event_botaoEntrarMousePressed

    private void painelLogoMousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:

    }

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        //int x = evt.getXOnScreen();
        //int y = evt.getYOnScreen();
        //this.setLocation(x - xx, y - xy);// TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    //int xx,xy;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        //xx = evt.getX();
        //xy = evt.getY();// TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
        new TelaCadastroUser().show();
    }//GEN-LAST:event_jLabel7MousePressed

    private void botaoEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEntrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEntrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botaoEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLfechar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel painelLogo;
    private javax.swing.JPanel painelLoguin;
    private javax.swing.JTextField vConta;
    private javax.swing.JTextField vSenha;
    // End of variables declaration//GEN-END:variables
}
